"""SocketCAN interface enumeration (sysfs + `ip`), USB-serial mapping, and bring-up helpers.

Nothing here changes system state; `bringup_commands` only *prints* the sudo commands.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

ARPHRD_CAN = "280"
DEFAULT_BITRATE = 1_000_000
SYS_NET = Path("/sys/class/net")


@dataclass
class CanIface:
    name: str
    up: bool
    bitrate: int | None
    serial: str | None
    product: str | None
    manufacturer: str | None
    usb_path: str | None
    rx_packets: int
    tx_packets: int
    bus_errors: int

    @property
    def state(self) -> str:
        return "UP" if self.up else "DOWN"


def _read(p: Path) -> str | None:
    try:
        return p.read_text().strip()
    except OSError:
        return None


def _ip_json(name: str) -> dict:
    if not shutil.which("ip"):
        return {}
    try:
        out = subprocess.run(
            ["ip", "-j", "-d", "link", "show", name], capture_output=True, text=True, check=True
        ).stdout
        rows = json.loads(out)
        return rows[0] if rows else {}
    except (subprocess.CalledProcessError, json.JSONDecodeError, IndexError):
        return {}


def list_can_interfaces(sys_net: Path = SYS_NET) -> list[CanIface]:
    ifaces: list[CanIface] = []
    for p in sorted(sys_net.iterdir()):
        if _read(p / "type") != ARPHRD_CAN:
            continue
        info = _ip_json(p.name)
        flags = info.get("flags", [])
        bitrate = None
        try:
            bitrate = int(info["linkinfo"]["info_data"]["bittiming"]["bitrate"])
        except (KeyError, TypeError, ValueError):
            pass
        serial = product = manufacturer = usb_path = None
        dev = p / "device"
        if dev.exists():
            usb = dev.resolve().parent  # .../3-1.2.2:1.0 -> .../3-1.2.2
            serial = _read(usb / "serial")
            product = _read(usb / "product")
            manufacturer = _read(usb / "manufacturer")
            usb_path = usb.name
        stats = p / "statistics"
        ifaces.append(
            CanIface(
                name=p.name,
                up="UP" in flags and "LOWER_UP" in flags,
                bitrate=bitrate,
                serial=serial,
                product=product,
                manufacturer=manufacturer,
                usb_path=usb_path,
                rx_packets=int(_read(stats / "rx_packets") or 0),
                tx_packets=int(_read(stats / "tx_packets") or 0),
                bus_errors=int(_read(stats / "rx_errors") or 0) + int(_read(stats / "tx_errors") or 0),
            )
        )
    return ifaces


def find_by_serial(serial: str, ifaces: list[CanIface] | None = None) -> CanIface | None:
    for i in ifaces if ifaces is not None else list_can_interfaces():
        if i.serial == serial:
            return i
    return None


def find_by_name(name: str, ifaces: list[CanIface] | None = None) -> CanIface | None:
    for i in ifaces if ifaces is not None else list_can_interfaces():
        if i.name == name:
            return i
    return None


def bringup_commands(names: list[str], bitrate: int = DEFAULT_BITRATE) -> list[str]:
    """Shell commands (need root) that bring interfaces up at the YAM bitrate."""
    cmds = []
    for n in names:
        cmds.append(f"sudo ip link set {n} down")
        cmds.append(f"sudo ip link set {n} up type can bitrate {bitrate}")
    return cmds


def udev_rules_text(serial_to_name: dict[str, str]) -> str:
    """udev rules giving adapters persistent names (optional; yamkit does not need them)."""
    lines = ["# /etc/udev/rules.d/90-yam-can.rules — generated by yamkit (not installed automatically)"]
    for serial, name in serial_to_name.items():
        if len(name) > 13:
            raise ValueError(f"CAN interface name {name!r} exceeds 13 characters")
        lines.append(f'SUBSYSTEM=="net", ACTION=="add", ATTRS{{serial}}=="{serial}", NAME="{name}"')
    return "\n".join(lines) + "\n"
