#!/usr/bin/env bash
# Install the pinned GPU inference runtime inside this checkout. No system or robot setup.
set -euo pipefail

if [[ "${1:-}" == --help || "${1:-}" == -h ]]; then
  printf '%s\n' 'Usage: scripts/setup_inference.sh' \
    'Installs repository-local uv, Python 3.12 and .venv-inference using the CUDA requirements.' \
    'Then source data/inference/env.sh. Does not start a model, server or robot.'
  exit 0
fi
if (( $# )); then
  printf '%s\n' 'Unexpected arguments; use --help.' >&2
  exit 2
fi

INFERENCE_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$INFERENCE_ROOT"
if [[ "$(uname -s)" != Linux || "$(uname -m)" != x86_64 ]]; then
  printf '%s\n' 'This pinned inference environment requires Linux x86_64.' >&2
  exit 1
fi
for source_file in configs/modal-requirements.txt src/yamkit/inference/service.py \
  plugins/lerobot_robot_yamkit/lerobot_robot_yamkit/yam_follower.py; do
  [[ -f "$source_file" ]] || { printf 'Full yamkit checkout required: missing %s\n' "$source_file" >&2; exit 1; }
done

# Existing symlinks must not redirect package/cache writes outside this checkout.
for local_path in .tools .uv-python .uv-cache .venv-inference data data/inference data/tmp \
  data/cache data/hf data/torch; do
  case "$(realpath -m -- "$local_path")" in
    "$INFERENCE_ROOT"/*) ;;
    *) printf 'Refusing path outside this checkout: %s\n' "$local_path" >&2; exit 1 ;;
  esac
done
mkdir -p .tools data/inference data/tmp data/cache data/hf data/torch

cat > data/inference/env.sh <<'ENV'
# Generated by scripts/setup_inference.sh; source this from Bash on the GPU host.
_yamkit_inference_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
export YAMKIT_ROOT="$_yamkit_inference_root"
export UV_PYTHON_INSTALL_DIR="$_yamkit_inference_root/.uv-python"
export UV_PYTHON_BIN_DIR="$_yamkit_inference_root/.tools"
export UV_CACHE_DIR="$_yamkit_inference_root/.uv-cache"
export UV_TOOL_DIR="$_yamkit_inference_root/data/uv-tools"
export UV_TOOL_BIN_DIR="$_yamkit_inference_root/.tools"
export UV_CREDENTIALS_DIR="$_yamkit_inference_root/data/uv-credentials"
export HF_HOME="$_yamkit_inference_root/data/hf"
export HF_LEROBOT_HOME="$_yamkit_inference_root/data/lerobot"
export TORCH_HOME="$_yamkit_inference_root/data/torch"
export XDG_CACHE_HOME="$_yamkit_inference_root/data/cache"
export XDG_DATA_HOME="$_yamkit_inference_root/data/xdg"
export XDG_CONFIG_HOME="$_yamkit_inference_root/data/config"
export PIP_CACHE_DIR="$_yamkit_inference_root/data/cache/pip"
export TRITON_CACHE_DIR="$_yamkit_inference_root/data/cache/triton"
export TORCHINDUCTOR_CACHE_DIR="$_yamkit_inference_root/data/cache/torchinductor"
export CUDA_CACHE_PATH="$_yamkit_inference_root/data/cache/cuda"
export TMPDIR="$_yamkit_inference_root/data/tmp"
export WANDB_DIR="$_yamkit_inference_root/outputs/wandb"
export HF_HUB_DISABLE_TELEMETRY=1
export TOKENIZERS_PARALLELISM=false
export PYTHONNOUSERSITE=1
export PYTHONPATH="$_yamkit_inference_root/src"
export VIRTUAL_ENV="$_yamkit_inference_root/.venv-inference"
export PATH="$_yamkit_inference_root/.venv-inference/bin:$_yamkit_inference_root/.tools:$PATH"
unset _yamkit_inference_root
ENV
# shellcheck disable=SC1091
source data/inference/env.sh

if [[ ! -x .tools/uv ]]; then
  command -v curl >/dev/null || { printf '%s\n' 'curl is required; no system packages were installed.' >&2; exit 1; }
  curl --fail --silent --show-error --location https://astral.sh/uv/install.sh -o .tools/install-uv.sh
  env UV_UNMANAGED_INSTALL="$INFERENCE_ROOT/.tools" UV_NO_MODIFY_PATH=1 sh .tools/install-uv.sh
fi
case "$(realpath -- .tools/uv)" in
  "$INFERENCE_ROOT"/*) ;;
  *) printf '%s\n' '.tools/uv must be installed inside this checkout.' >&2; exit 1 ;;
esac

.tools/uv --no-config python install 3.12
if [[ ! -e .venv-inference ]]; then
  .tools/uv --no-config venv --managed-python --python 3.12 .venv-inference
elif [[ ! -f .venv-inference/pyvenv.cfg ]]; then
  printf '%s\n' '.venv-inference exists but is not a virtual environment; refusing to overwrite it.' >&2
  exit 1
fi
case "$(realpath -- .venv-inference/bin/python)" in
  "$INFERENCE_ROOT"/.uv-python/*) ;;
  *) printf '%s\n' 'Inference Python must come from the .uv-python directory in this checkout.' >&2; exit 1 ;;
esac
.venv-inference/bin/python -c 'import sys; assert sys.version_info[:2] == (3, 12), "Python 3.12 is required"'

# Match Modal's pinned CUDA environment. --no-config excludes the CPU index in pyproject.toml.
# All entries are pinned; matching pip across the two declared indexes avoids first-index shadowing.
.tools/uv --no-config pip sync --python .venv-inference/bin/python \
  --index-strategy unsafe-best-match configs/modal-requirements.txt
# The same small HTTP layer installed by modal_service.py, constrained by the shared runtime pins.
.tools/uv --no-config pip install --python .venv-inference/bin/python \
  --index-strategy unsafe-best-match --constraint configs/modal-requirements.txt \
  'uvicorn==0.52.4' 'h11==0.16.0'
.tools/uv --no-config pip check --python .venv-inference/bin/python

printf '\n%s\n' 'Inference environment ready. Source data/inference/env.sh before using .venv-inference/bin/python.' \
  'No model/server was started. Stop any existing inference process before changing its environment.'
